name: Build + Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.git**'
      - 'service/**'
      - '**.md'
      - 'LICENSE'
  workflow_dispatch:
    inputs:
      version:
        description: 'release version'
        required: false
        default: 'latest'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: setup nodejs
        uses: actions/setup-node@main
        with:
          node-version: 'latest'

      - name: setup go
        uses: actions/setup-go@main
        with:
          go-version: 'stable'

      - name: processing
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # 下载源代码
          version="$(curl -s https://thekelleys.org.uk/dnsmasq/ | grep -Eo 'dnsmasq-[0-9]+\.[0-9]+\.tar\.gz' | cut -d- -f2 | cut -d. -f1-2 | tail -n1)"
          curl -sL "https://thekelleys.org.uk/dnsmasq/dnsmasq-$version.tar.gz" | tar -zxvC ./

          # 编译
          cd ./dnsmasq-* || exit 1
          make -j "$(nproc)" CFLAGS="-Os" LDFLAGS="-static"
          
          # 编译后文件打包
          mv src/dnsmasq . && gzip -9 dnsmasq
          
          # delete all releases and their tags
          gh release list | awk -F '\t' '{print $3}' | while read -r line; do gh release delete --yes --cleanup-tag "$line"; done

          # create release
          if [ "${{ inputs.version }}" != "" ]; then
            tag="${{ inputs.version }}"
          else
            tag="$version"
          fi
          gh release create "$tag" --generate-notes "dnsmasq.gz"
